// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSTc6lgXS51VgpT9wnCe5infM54fFQWl8',
    appId: '1:407390589948:web:c52716f34c988f1d43d879',
    messagingSenderId: '407390589948',
    projectId: 'garbagecollectionsystem-bba0d',
    authDomain: 'garbagecollectionsystem-bba0d.firebaseapp.com',
    storageBucket: 'garbagecollectionsystem-bba0d.appspot.com',
    measurementId: 'G-5YDR4B1ZR8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFZiDlioDN8UD1nBuuRxsSEuwGsxKPbu4',
    appId: '1:407390589948:android:e11ed48e877a724643d879',
    messagingSenderId: '407390589948',
    projectId: 'garbagecollectionsystem-bba0d',
    storageBucket: 'garbagecollectionsystem-bba0d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD99aT_nyCVrNJD7jB3-tcaSlu_f_8IFzY',
    appId: '1:407390589948:ios:d9b8baf0fe49923543d879',
    messagingSenderId: '407390589948',
    projectId: 'garbagecollectionsystem-bba0d',
    storageBucket: 'garbagecollectionsystem-bba0d.appspot.com',
    iosBundleId: 'com.techvisionaries.trashtrekSpm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD99aT_nyCVrNJD7jB3-tcaSlu_f_8IFzY',
    appId: '1:407390589948:ios:d9b8baf0fe49923543d879',
    messagingSenderId: '407390589948',
    projectId: 'garbagecollectionsystem-bba0d',
    storageBucket: 'garbagecollectionsystem-bba0d.appspot.com',
    iosBundleId: 'com.techvisionaries.trashtrekSpm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSTc6lgXS51VgpT9wnCe5infM54fFQWl8',
    appId: '1:407390589948:web:a516203aa8a3b6c043d879',
    messagingSenderId: '407390589948',
    projectId: 'garbagecollectionsystem-bba0d',
    authDomain: 'garbagecollectionsystem-bba0d.firebaseapp.com',
    storageBucket: 'garbagecollectionsystem-bba0d.appspot.com',
    measurementId: 'G-S1T5R09LLD',
  );
}
